services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bimba-ksr-app
    ports:
      - "8181:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=adminlte_db
      - DB_PORT=3306
      - DB_NAME=bimba_ksr
      - DB_USER=bimba
      - DB_PASS=merdeka1945
      - TZ=Asia/Jakarta          # ← tambahan timezone
    networks:
      - admin-lte-web_default
    restart: unless-stopped

networks:
  admin-lte-web_default:
    external: true